SET IDENTITY_INSERT [dbo].[StudyFields] ON
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (1, N'Modern Language-Sciences', N'The Modern Languages Sciences direction targets students with a clear preference for languages and sciences who also have a thorough knowledge of mathematics. Students should be able to solve a problem independently, look for data and work as part of a team. The latter aspect is especially prevalent during science work classes, where they conduct experiments in small groups. Students should be aware that this is a transfer direction.', 1, N'Moderne talen - wetenschappen.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (2, N'Engineering Sciences', N'You have a strong interest in sciences and possess theoretical understanding of biology, chemistry and physics. You are good at math and curious about scientific applications. You enjoy working in a laboratory where you test theory against reality through experiments.', 3, N'techniek- wetenschapppen.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (3, N'Science Mathematics', N'The sciences direction targets students with a clear preference for sciences who also have a thorough knowledge of mathematics. Students should be able to solve a problem independently, look for data and work as part of a team. The latter aspect is especially addressed during science work classes, where they conduct experiments in small groups. Students should be aware that this is a transfer direction.', 3, N'techniek- wetenschapppen.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (4, N'Latin mathematics', N'Classics is a field of study for students with an aptitude for languages and a very broad cultural interest. Studying Latin is not only about learning ancient languages, it also teaches you problem-solving skills. Moreover, it is good practice for learning modern foreign languages such as Spanish, French and Italian. After this major, you can move on to college or university. Possible study choices include history, medicine, pharmaceutical sciences, engineering, law, biomedical sciences, mathematics, physics and astronomy, computer science, industrial sciences, engineering, architecture, ...', 3, N'Latijn.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (5, N'Latin - Modern Languages', N'Classics is a field of study for students with an aptitude for languages and a very broad cultural interest. Studying Latin is not only about learning ancient languages, it also teaches you problem-solving skills. Moreover, it is good practice for learning modern foreign languages such as Spanish, French and Italian. After this major, you can move on to college or university. Possible study choices are: history, language & literature, law, ... ', 1, N'Latijn.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (6, N'latin -  Sciences', N'Classics is a field of study for students with an aptitude for languages, sciences and a very broad cultural interest. Studying Latin is not only about learning ancient languages, it also teaches you problem-solving skills. Moreover, it is good practice for learning modern foreign languages such as Spanish, French and Italian. After this major, you can move on to college or university. Possible study choices are: translator interpreter, history, medicine, pharmaceutical sciences, engineering, language & literature, law, biomedical sciences, ...', 3, N'Latijn.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (7, N'Human Sciences', N'You are bitten to know. Also not afraid to turn everything inside out and reflect on yourself and others. You can handle language and theory. You follow what is happening in current affairs. What is opinion? What is fact? We teach you to read between the lines and see connections.  Open-minded and curious? We prepare you from this broad base for your further school career, at college or university. As a pathway, the human sciences course aims to offer students a broad education and prepare them for higher education (both university and college). You have a high capacity for abstraction and an interest in human behavior in all its aspects. You have an interest in art and culture. ', 2, N'humane- wetenschappen.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (8, N'Tourism', N'Who wouldn''t want to check on the spot if a smos was invented on the Sandwich Islands? Easter eggs, you just look for them on Easter Island, right? Would there also be Burger Kings on the McDonald Islands? You get it: you were born with a travel bug.
You have a talent for language and want to learn to speak, write, listen and read fluently in French, English, German and Spanish. Teamwork and organization: that''s what you love.', 2, N'toerisme.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (9, N'Economics - Mathematics', N'Students choose this direction because of their interest in business, commerce and finance. They should be aware that this is a transfer direction. That is, the formation is aimed at further study in higher education and not the job market or employment at 18.', 4, N'Economie- wiskunde.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (10, N'Economy - Modern Languages', N'Students choose this direction because of their interest in business, commerce and finance. They should be aware that this is a transfer direction. That is, the formation is aimed at further study in higher education and not the job market or employment at 18. After this course of study, you can move on to college or university. Possible study choices are: law, languages, economic sciences, business management, ...', 4, N'Economie- wiskunde.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (12, N'Commerce', N'Thinking and dreaming is nice, but you are a doer who makes decisions. You like to work out the theory you learn in concrete terms. Business and Organization offers a broad theoretical basis: from accounting to sales calls, from economics to practical triage. With that knowledge, you''ll be ready to show your worth during company internships. In all of this, you like to be concerned with the "pennies" - income and expenses must be right!', 4, N'Handel.png')
INSERT INTO [dbo].[StudyFields] ([Id], [Name], [Description], [FieldId], [IconName]) VALUES (13, N'Logistical Maritime Administration', N'This field of study is aimed at students interested in executive work in the areas of administrative, logistics and commercial services. Writing and speaking languages correctly are important skills. In addition, you have a sense of order and can work both independently and as part of a team.', 5, N'Handel.png')
SET IDENTITY_INSERT [dbo].[StudyFields] OFF
